# Generated by Django 5.0 on 2024-01-03 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Counrse_name',
            new_name='Course_name',
        ),
    ]
