# Generated by Django 5.0 on 2024-01-04 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0002_rename_counrse_name_course_course_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermember',
            old_name='user',
            new_name='userr',
        ),
    ]
